spring.application.name=minutemind

# Database Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=${MAX_POOL_SIZE}
spring.datasource.hikari.minimum-idle=${MIN_IDLE}
spring.datasource.hikari.connection-timeout=${CONNECTION_TIMEOUT}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

springdoc.swagger-ui.path=/swagger-ui/index.html

server.servlet.context-path=${CONTEXT_PATH}

# Redis Configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=3000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2

# App Custom Properties
app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-expiry=${JWT_TOKEN_EXPIRY}
app.jwt.refresh-token-expiry=${JWT_FTOKEN_EXPIRY}
app.cors.allowed-origins=${CORS_ORIGINS}

# Cloudinary
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
cloudinary.folder=${CLOUDINARY_FOLDER}